.PHONY: clean All

All:
	@echo "----------Building project:[ UnitTest - Debug ]----------"
	@cd "/home/stud/C++Projects/Kursach!client/UnitTest/UnitTest" && "$(MAKE)" -f  "UnitTest.mk"
clean:
	@echo "----------Cleaning project:[ UnitTest - Debug ]----------"
	@cd "/home/stud/C++Projects/Kursach!client/UnitTest/UnitTest" && "$(MAKE)" -f  "UnitTest.mk" clean
