.PHONY: clean All

All:
	@echo "----------Building project:[ Kursach - Debug ]----------"
	@cd "/home/stud/C++Projects/Kursach!client/Kursach/Kursach" && "$(MAKE)" -f  "Kursach.mk"
clean:
	@echo "----------Cleaning project:[ Kursach - Debug ]----------"
	@cd "/home/stud/C++Projects/Kursach!client/Kursach/Kursach" && "$(MAKE)" -f  "Kursach.mk" clean
